/**
 * Detailed content for the 30 STEM experience programmes.
 *
 * UNLIKE `courseDetails.en.js`, which is GENERATED by the LearnPress scraper, this
 * file is **hand-written** from the official catalogue supplied by FabLab EIU. It
 * lives separately so re-running the scraper never touches it.
 *
 * ⚠️ These are project translations of the Vietnamese catalogue, **not** the
 * university's own English copy. Have them reviewed before going to production.
 *
 * Each programme has exactly four `curriculum` lines, mirroring the Vietnamese file.
 * There is no `overview` / `knowledge` / `skills` / `sourceUrl`: the catalogue does
 * not supply those, and the modal only renders sections that have data.
 */
export const experienceDetailsEn = {
  // --- Natural science & life ----------------------------------------------
  'thien-nhien': {
    curriculum: [
      'Learn about the seasons of the year.',
      'Learn about weather phenomena, natural disasters and how they form.',
      'Explore the impact of natural disasters and how to prevent and respond to them.',
      'Build a working model that simulates a natural disaster.',
    ],
  },
  'nang-luong-cuoc-song': {
    curriculum: [
      'Learn about the different forms of energy and where energy comes from.',
      'Learn how energy is transferred.',
      'Explore how energy is converted from one form to another.',
      'Take on the "One-touch machine" game challenge.',
    ],
  },
  'am-thanh': {
    curriculum: [
      'Learn about sound sources and the vibrations that create sound.',
      'Learn how sound travels and which media carry it.',
      'Explore how the ear picks up sound and sends signals to the brain.',
      'Practise transmitting sound through an interactive game.',
    ],
  },
  'nam-cham': {
    curriculum: [
      'Learn about magnetic fields and their role in nature and daily life.',
      'Explore the relationship between magnets and magnetic fields.',
      'Run experiments on the basic properties of magnets.',
      'Take on the "Magnetic force" game challenge.',
    ],
  },
  'cap-quang': {
    curriculum: [
      'Learn about the refraction of light and total internal reflection.',
      'Explore how light travels through an optical fibre.',
      'Run experiments transmitting light using refraction and total internal reflection.',
      'Take on the Morse code message challenge.',
    ],
  },
  polymer: {
    curriculum: [
      'Learn about polymers and their role in daily life.',
      'Explore the characteristics and applications of the polymer material families.',
      'Run hands-on experiments with polymer materials.',
      'Take on the challenge of making a biopolymer plastic.',
    ],
  },
  'nang-luong-tai-tao': {
    curriculum: [
      'Learn about renewable energy sources.',
      'Learn how wind energy is converted into electricity.',
      'Explore how a wind turbine works.',
      'Measure the electricity produced by a renewable energy model.',
    ],
  },
  'moi-truong-nuoc': {
    curriculum: [
      'Learn what causes water pollution.',
      'Explore the methods used to treat wastewater.',
      'Run experiments: measuring pH, disinfecting and decolourising water, testing pool water.',
      'Apply the experiment kit to treat water.',
    ],
  },
  'nganh-nhua': {
    curriculum: [
      'Learn what polymers are and how they are classified.',
      'Learn about the physical and chemical properties of polymers.',
      'Explore the difference between synthesising and processing polymers.',
      'Sort plastics by type and run polymer-making experiments.',
    ],
  },

  // --- Engineering & robotics ----------------------------------------------
  'xe-robot': {
    curriculum: [
      'Learn about the parts of a robot car and what each one does.',
      'Explore how to drive a robot car by voice and by remote control.',
      'Drive the robot car around a track and over obstacles.',
      'Take on the "Robot race track" challenge.',
    ],
  },
  drone: {
    curriculum: [
      'Learn about drones and how they are used in the real world.',
      'Explore the principles of drone flight.',
      'Practise programming a drone to fly.',
      'Try out the Drone Soccer challenge.',
    ],
  },
  'canh-tay-robot': {
    curriculum: [
      'Learn about the characteristics and uses of robot arms in manufacturing.',
      'Explore how a robot arm is built and how it works.',
      'Practise programming a robot arm.',
      'Take on the "Colour sorting station" game challenge.',
    ],
  },
  'robot-sinh-hoc': {
    curriculum: [
      'Learn to recognise different animal and plant species.',
      'Explore how a biological robot model works.',
      'Assemble and operate a biological robot model.',
      'Play a game using the biological robot model.',
    ],
  },
  'kham-pha-dien': {
    curriculum: [
      'Learn what a power source is and what electrical components do.',
      'Learn the safety rules for working with electricity.',
      'Explore the function of common electrical devices and basic electronic components.',
      'Assemble a basic circuit and test that it works.',
    ],
  },
  'thiet-ke-co-khi': {
    curriculum: [
      'Learn about technical drawings, projections and drawing conventions.',
      'Explore how to read and analyse a technical drawing.',
      'Design a sample product.',
      'Machine and assemble the product from the drawing.',
    ],
  },
  'co-dien-tu': {
    curriculum: [
      'Learn about mechatronics and where it is used in practice.',
      'Learn about production lines and their basic components.',
      'Explore the programming software and its control blocks.',
      'Program and control mechatronic modules.',
    ],
  },
  'co-hoc-sang-tao': {
    curriculum: [
      'Learn about force and moment of force.',
      'Explore how a few simple machines work.',
      'Use simple machines in a model that raises and lowers a load.',
      'Apply what you know about force and simple machines to explain how a lift model works.',
    ],
  },
  cnc: {
    curriculum: [
      'Learn about mechanical machining.',
      'Explore how a CNC milling machine is built and how it works.',
      'Draw a simple mechanical drawing.',
      'Operate the CNC machine to machine a product.',
    ],
  },
  'in-3d': {
    curriculum: [
      'Learn about additive manufacturing — 3D printing.',
      'Explore how a 3D printer is built and how it works.',
      'Prepare the file and tune the print settings for each product.',
      'Operate the 3D printer to print a product.',
    ],
  },
  'muc-nuoc-thong-minh': {
    curriculum: [
      'Get an overview of water level control systems and their real-world uses.',
      'Explore pump motor control and reading sensor data.',
      'Apply feedback control to hold the water level at a target.',
      'Use voice recognition to command the water level and query the system.',
    ],
  },

  // --- AIoT & digital technology -------------------------------------------
  'lam-quen-ai': {
    curriculum: [
      'Learn what artificial intelligence (AI) is.',
      'Explore where AI shows up in everyday life.',
      'Simulate how an AI learns from data.',
      'Take on the "What did the AI learn?" game challenge.',
    ],
  },
  'the-gioi-ao': {
    curriculum: [
      'Learn what programming does in robot control.',
      'Explore the programming software and its basic command blocks.',
      'Program a robot to move around a simulated field.',
      'Apply what you have learned in the "Master farm engineer" project.',
    ],
  },
  'noi-dung-so': {
    curriculum: [
      'Learn the difference between generative AI and traditional AI.',
      'Explore how to write a good prompt to generate images with AI.',
      'Learn how to assemble a video from images and sound.',
      'Build a short story using purpose-built tools.',
    ],
  },
  'cau-truc-may-tinh': {
    curriculum: [
      'Learn the structure of a computer and what its main components do.',
      'Learn the role of each part: CPU, mainboard, RAM, SSD/HDD and so on.',
      'Explore how to choose components and hardware that fit a given need.',
      'Pick a set of components suited to a specific purpose.',
    ],
  },
  'thiet-ke-3d': {
    curriculum: [
      'Learn about 3D design.',
      'Learn about the coordinate system in three-dimensional space.',
      'Explore the tools used to design for 3D printing.',
      'Create a 3D design using purpose-built software.',
    ],
  },
  blockchain: {
    curriculum: [
      'Learn the history of money, from its earliest forms to the digital era.',
      'Learn about blockchain technology through cryptocurrency.',
      'Understand how blockchain stays secure through hash links between blocks.',
      'Simulate block validation on a blockchain.',
    ],
  },
  iot: {
    curriculum: [
      'Learn the principles behind connecting and controlling IoT devices.',
      'Explore app interface programming and the role of cloud storage platforms.',
      'Design a control app interface.',
      'Program and control an IoT model through a smart interface.',
    ],
  },
  'thi-giac-may-tinh': {
    curriculum: [
      'Get a brief introduction to machine learning.',
      'Explore what machine learning is for and how it is categorised in practice.',
      'Work through a machine learning pipeline using a convolutional neural network.',
      'Apply machine learning to object recognition.',
    ],
  },
  'xac-suat-hoc-may': {
    curriculum: [
      'Learn about the Naïve Bayes theorem.',
      'Collect and analyse historical customer data.',
      'Apply the Naïve Bayes algorithm to predict customer behaviour from that data.',
      'Evaluate performance based on accuracy.',
    ],
  },
  'thiet-ke-website': {
    curriculum: [
      'Learn the basic concepts of user interface and user experience.',
      'Explore the website interface design process.',
      'Explore the core features of the tools used for website design.',
      'Design a simple website.',
    ],
  },
}
